services:

    mariadb:
        container_name: ${PROJECT_NAME}-mariadb
        image: ${PROJECT_NAME}-mariadb:${PROJECT_NAME}-${PROJECT_VERSION}
        build:
            context: .
            dockerfile: ${MARIADB_DOCKERFILE}/Dockerfile
        ports:
            - "${MARIADB_PORT}:${MARIADB_PORT}"
        environment:
            MYSQL_DATABASE: ${MARIADB_DATABASE}
            MYSQL_USER: ${MARIADB_USERNAME}
            MYSQL_PASSWORD: ${MARIADB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
        networks:
            - unified
        volumes:
            - database:/var/lib/mysql

    phpmyadmin:
        container_name: ${PROJECT_NAME}-phpmyadmin
        image: ${PROJECT_NAME}-phpmyadmin:${PROJECT_NAME}-${PROJECT_VERSION}
        build:
            context: .
            dockerfile: ${PHPMYADMIN_DOCKERFILE}/Dockerfile
        ports:
            - "${PHPMYADMIN_PORT}:${PHPMYADMIN_PORT_MAP}"
        environment:
            PMA_HOST: ${PHPMYADMIN_PMA_HOST}
            PMA_USER: ${MARIADB_USERNAME}
            PMA_PASSWORD: ${MARIADB_PASSWORD}
        networks:
            - unified
        depends_on:
            - mariadb

    nuxt:
        container_name: ${PROJECT_NAME}-nuxt
        image: ${PROJECT_NAME}-nuxt:${PROJECT_NAME}-${PROJECT_VERSION}
        build:
            context: .
            dockerfile: ${NODE_DOCKERFILE}/Dockerfile
        ports:
            - "${NODE_CLIENT_PORT}:${NODE_CLIENT_PORT}"
            - "24678:24678"
        volumes:
            - ${NODE_CLIENT_DIRECTORY}:${NODE_CLIENT_WORK_DIRECTORY}
        working_dir: ${NODE_CLIENT_WORK_DIRECTORY}
        command: /bin/sh -c "npm install && npm run dev"
        environment:
            - NUXT_PORT=${NODE_CLIENT_PORT}
            - NUXT_HOST=0.0.0.0

    express:
        container_name: ${PROJECT_NAME}-express
        image: ${PROJECT_NAME}-express:${PROJECT_NAME}-${PROJECT_VERSION}
        build:
            context: .
            dockerfile: ${NODE_DOCKERFILE}/Dockerfile
        ports:
            - "${NODE_SERVER_PORT}:${NODE_SERVER_PORT}"
        volumes:
            - ${NODE_SERVER_DIRECTORY}:${NODE_SERVER_WORK_DIRECTORY}
        working_dir: ${NODE_SERVER_WORK_DIRECTORY}
        command: /bin/sh -c "npm install && npm run dev"
        environment:
            - EXPRESS_PORT=${NODE_SERVER_PORT}
            - DATABASE_URL=${MARIADB_URL}

networks:
    unified:
        name: ${PROJECT_NAME}-network
        driver: bridge

volumes:
    database:
        name: ${PROJECT_NAME}-database
        driver: local